version: "3.7"

services:
  frontend:
    image: flux-web-auth-frontend:next
    env_file:
      - frontend.env

  backend:
    image: flux-web-auth-backend:next
    env_file:
      - backend.env

  envoy:
    image: envoyproxy/envoy-distroless:v1.22-latest
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml

  caddy:
    image: caddy:2.5.1-alpine
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "30000:80"
