name: Build Docker Image
on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ github.event.repository.name }}:${{ github.ref_name }}
          outputs: type=tar,dest=./docker-image.tar

      - name: Pack Image
        run: gzip ./docker-image.tar

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image.tar.gz
          path: ./docker-image.tar.gz

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Image
        uses: actions/download-artifact@v3
        with:
          name: docker-image.tar.gz

      - name: Rename Image
        run: mv docker-image.tar.gz ${{ github.event.repository.name }}_${{ github.ref_name }}_image.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: "*.tar.gz"
